import 'dart:io';
import 'package:path/path.dart' as p;

class AssetPipeline {
  static Future<void> sync() async {
    print('🖼️ Syncing assets to pubspec.yaml and generating AppAssets...');
    
    final assetDir = Directory('assets');
    if (!assetDir.existsSync()) {
      assetDir.createSync();
    }

    final assets = _listAssets(assetDir);
    if (assets.isEmpty) {
      print('ℹ️ No assets found in assets/ folder.');
      return;
    }

    await _updatePubspec(assets);
    await _generateDartClass(assets);
    
    print('✅ Asset sync complete!');
  }

  static List<String> _listAssets(Directory dir) {
    return dir.listSync(recursive: true)
        .whereType<File>()
        .map((file) => p.relative(file.path, from: Directory.current.path).replaceAll('\\', '/'))
        .toList();
  }

  static Future<void> _updatePubspec(List<String> assets) async {
    final pubspec = File('pubspec.yaml');
    if (!pubspec.existsSync()) return;

    var lines = pubspec.readAsLinesSync();
    
    int flutterIndex = -1;
    int assetsIndex = -1;

    for (int i = 0; i < lines.length; i++) {
      if (lines[i].trim() == 'flutter:') flutterIndex = i;
      if (lines[i].trim() == 'assets:') assetsIndex = i;
    }

    if (assetsIndex != -1) {
      // Remove old assets section
      int endAssets = assetsIndex + 1;
      while (endAssets < lines.length && (lines[endAssets].trim().startsWith('-') || lines[endAssets].trim().isEmpty)) {
        endAssets++;
      }
      lines.removeRange(assetsIndex, endAssets);
    }

    // Re-find flutter index after removal
    flutterIndex = lines.indexWhere((l) => l.trim() == 'flutter:');

    if (flutterIndex != -1) {
      lines.insert(flutterIndex + 1, '  assets:');
      for (int i = 0; i < assets.length; i++) {
        lines.insert(flutterIndex + 2 + i, '    - ${assets[i]}');
      }
    } else {
      lines.add('\nflutter:');
      lines.add('  assets:');
      for (var asset in assets) {
        lines.add('    - $asset');
      }
    }

    pubspec.writeAsStringSync(lines.join('\n'));
    print('✅ pubspec.yaml updated.');
  }

  static Future<void> _generateDartClass(List<String> assets) async {
    final file = File('lib/core/constants/app_assets.dart');
    if (!file.parent.existsSync()) file.parent.createSync(recursive: true);

    final buffer = StringBuffer();
    buffer.writeln('// GENERATED BY FEX ASSET PIPELINE');
    buffer.writeln('class AppAssets {');
    
    for (var asset in assets) {
      final fileName = p.basenameWithoutExtension(asset).replaceAll('-', '_').replaceAll(' ', '_').toLowerCase();
      buffer.writeln('  static const String $fileName = \'$asset\';');
    }
    
    buffer.writeln('}');
    file.writeAsStringSync(buffer.toString());
  }
}
