import 'dart:io';
import 'package:path/path.dart' as p;

class AssetPipeline {
  static Future<void> sync() async {
    print('🖼️ Syncing assets to pubspec.yaml and generating AppAssets...');
    
    final assetDir = Directory('assets');
    if (!assetDir.existsSync()) {
      assetDir.createSync();
      print('ℹ️ Created assets/ directory.');
    }

    final assets = _listAssets(assetDir);
    await _updatePubspec(assets);
    await _generateDartClass(assets);
    
    print('✅ Asset sync complete!');
  }

  static List<String> _listAssets(Directory dir) {
    return dir.listSync(recursive: true)
        .whereType<File>()
        .map((file) => p.relative(file.path, from: Directory.current.path).replaceAll('\\', '/'))
        .toList();
  }

  static Future<void> _updatePubspec(List<String> assets) async {
    final pubspec = File('pubspec.yaml');
    if (!pubspec.existsSync()) return;

    var lines = pubspec.readAsLinesSync();
    var newLines = <String>[];
    bool inAssets = false;
    bool assetsProcessed = false;

    for (var line in lines) {
      if (line.trim() == 'assets:') {
        inAssets = true;
        newLines.add(line);
        for (var asset in assets) {
          newLines.add('    - $asset');
        }
        assetsProcessed = true;
        continue;
      }

      if (inAssets && (line.startsWith('  -') || line.trim().isEmpty)) {
        continue; // Skip old asset lines
      } else {
        inAssets = false;
      }

      newLines.add(line);
    }

    // If no assets section found, add it
    if (!assetsProcessed) {
      newLines.add('\nflutter:');
      newLines.add('  assets:');
      for (var asset in assets) {
        newLines.add('    - $asset');
      }
    }

    pubspec.writeAsStringSync(newLines.join('\n'));
    print('✅ pubspec.yaml updated with ${assets.length} assets.');
  }

  static Future<void> _generateDartClass(List<String> assets) async {
    final file = File('lib/core/constants/app_assets.dart');
    if (!file.parent.existsSync()) file.parent.createSync(recursive: true);

    final buffer = StringBuffer();
    buffer.writeln('// GENERATED BY FEX ASSET PIPELINE');
    buffer.writeln('class AppAssets {');
    
    for (var asset in assets) {
      final fileName = p.basenameWithoutExtension(asset).replaceAll('-', '_').replaceAll(' ', '_');
      buffer.writeln('  static const String $fileName = \'$asset\';');
    }
    
    buffer.writeln('}');
    file.writeAsStringSync(buffer.toString());
    print('✅ lib/core/constants/app_assets.dart generated.');
  }
}
