import 'dart:io';

class EnvManager {
  static const String envPrefix = '.fex.env';

  static Future<void> setup() async {
    print('🔐 Setting up FEX Environment Manager...');

    final flavors = ['dev', 'staging', 'prod'];
    for (var flavor in flavors) {
      final fileName = '$envPrefix.$flavor';
      final file = File(fileName);
      if (!file.existsSync()) {
        file.writeAsStringSync(
            'BASE_URL=https://$flavor.api.example.com\nAPI_KEY=your_${flavor}_key_here\n');
        print('✅ Created $fileName');
      }
    }

    _ensureGitignore();
  }

  static Future<void> generate() async {
    print('⚙️ Generating lib/config/app_config.dart...');

    final configFile = File('lib/config/app_config.dart');
    if (!configFile.parent.existsSync()) {
      configFile.parent.createSync(recursive: true);
    }

    // Default to dev for generation base
    final devEnv = File('$envPrefix.dev');
    if (!devEnv.existsSync()) {
      print('❌ Error: .fex.env.dev not found. Run "fex env setup" first.');
      return;
    }

    final lines = devEnv.readAsLinesSync();
    final buffer = StringBuffer();

    buffer.writeln('// GENERATED BY FEX CLI - DO NOT MODIFY BY HAND');
    buffer.writeln('class AppConfig {');

    for (var line in lines) {
      if (line.trim().isEmpty || line.startsWith('#')) continue;
      final parts = line.split('=');
      if (parts.length >= 2) {
        final key = parts[0].trim();
        buffer.writeln(
            '  static const String ${key.toLowerCase()} = String.fromEnvironment(\'$key\');');
      }
    }

    buffer.writeln('}');
    configFile.writeAsStringSync(buffer.toString());
    print('🚀 AppConfig generated successfully!');
  }

  static void _ensureGitignore() {
    final gitignore = File('.gitignore');
    if (gitignore.existsSync()) {
      final content = gitignore.readAsStringSync();
      if (!content.contains(envPrefix)) {
        gitignore.writeAsStringSync('\n# FEX Secrets\n$envPrefix.*\n',
            mode: FileMode.append);
        print('🛡️ Added $envPrefix.* to .gitignore');
      }
    }
  }

  static Future<void> check(String flavor) async {
    final file = File('$envPrefix.$flavor');
    if (!file.existsSync()) {
      print('⚠️ Environment file for "$flavor" is missing!');
      return;
    }
    print('✅ Environment "$flavor" is valid.');
  }
}
